name: Example Workflow

on:
  workflow_call:
  push:
  workflow_dispatch:

jobs:
  process_A:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context (Process A)
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"

  process_B:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context (Process B)
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
