name: Test Event Workflow

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  workflow_call:
    uses: ./.github/workflows/test_event_name_2.yaml
    with:
      call_flag: true
  repository_dispatch:
    needs: workflow_call
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: peter-evans/repository-dispatch@v3
      with:
        repository: ${{ github.repository_owner }}/public_test_repo
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: test
        client-payload: '{"call_flag": true}'
