name: Example Workflow

on:
  workflow_call:
    inputs:
      call_flag:
        required: false
        type: boolean
        default: false
  push:
  workflow_dispatch:

jobs:
  process_A:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context (Process A)
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"

  process_B:
    if : ${{ inputs.call_flag == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context (Process B)
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
